apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sleep-daemonset
  namespace: node-specific-sizing
  labels:
    app: sleep
spec:
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
        node-specific-sizing.manomano.tech/enabled: "true"
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        node-specific-sizing.manomano.tech/request-cpu-fraction: "0.1"
        node-specific-sizing.manomano.tech/maximum-cpu: "1"
        # node-specific-sizing.manomano.tech/limit-cpu-fraction: "0.1"
        # node-specific-sizing.manomano.tech/request-memory-fraction: "0.8"
        # node-specific-sizing.manomano.tech/limit-memory-fraction: "0.1"
        # node-specific-sizing.manomano.tech/minimum-memory: 200Mi
        node-specific-sizing.manomano.tech/request-memory-fraction: "0.1"
        node-specific-sizing.manomano.tech/maximum-memory: 500Mi
    spec:
      terminationGracePeriodSeconds: 0
      priorityClassName: system-node-critical
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      # - effect: NoSchedule
      #   key: node.kubernetes.io/role
      #   operator: Exists
      # - effect: NoSchedule
      #   key: node.kubernetes.io/arch
      #   operator: Exists
      initContainers:
        - name: fetch-instance-data
          image: curlimages/curl:7.85.0
          command:
            - "sh"
            - "-c"
            - |
              echo "Fetching instance metadata..."
              echo "Instance Type: $(curl -s http://169.254.169.254/latest/meta-data/instance-type)"
              echo "CPU Details: $(grep -c ^processor /proc/cpuinfo) CPUs"
              echo "Memory Details: $(grep MemTotal /proc/meminfo | awk '{print $2}') KiB"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      containers:
        - name: sleep-a
          image: alpine
          command:
            - "sleep"
            - "infinity"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          #   limits:
          #     cpu: 30m
          #     memory: 200Mi
        - name: sleep-b
          image: alpine
          command:
            - "sleep"
            - "infinity"
          resources:
            requests:
              cpu: 100m
              memory: 600Mi
            # limits:
            #   cpu: 270m
            # memory: 1800Mi
