kind: Issuer
apiVersion: cert-manager.io/v1
metadata:
  name: node-specific-sizing-ca-bootstrap
  namespace: node-specific-sizing
spec:
  selfSigned: {}
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: node-specific-sizing-ca-root
  namespace: node-specific-sizing
spec:
  secretName: node-specific-sizing-ca-root
  isCA: true
  commonName: node-specific-sizing-ca-root
  subject:
    countries: [ "AU" ]
    organizations: [ "Entain Internal" ]
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    kind: Issuer
    name: node-specific-sizing-ca-bootstrap
---
kind: Issuer
apiVersion: cert-manager.io/v1
metadata:
  name: node-specific-sizing-ca-root
  namespace: node-specific-sizing
spec:
  ca:
    secretName: node-specific-sizing-ca-root
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-specific-sizing-serving-cert
  namespace: node-specific-sizing
spec:
  dnsNames:
    - node-specific-sizing.node-specific-sizing.svc
    - node-specific-sizing.node-specific-sizing.svc.cluster.local
  issuerRef:
    name: node-specific-sizing-ca-root
    kind: Issuer
  secretName: node-specific-sizing-serving-cert
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 2160h
  renewBefore: 360h
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: node-specific-sizing-client-cert
  namespace: node-specific-sizing
spec:
  issuerRef:
    name: node-specific-sizing-ca-root
    kind: Issuer
  commonName: api-server-client-cert-for-node-specific-sizing
  secretName: node-specific-sizing-client-cert
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - client auth
    - server auth
