apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-specific-sizing

resources:
- certmanager.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- serviceaccount.yaml
- mutatingadmissionwebhook.yaml
- service.yaml

labels:
  - pairs:
      app: node-specific-sizing
      user: mark-lynch