apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ default "443" .Values.service.port }}
      targetPort: {{ default "8443" .Values.service.targetPort }}
      protocol: TCP
      name: {{default (include "chart.fullname" .) .Values.service.portName }}
